### PR TITLE
valset: Don't include SimulateActiveValidators by default

### LINKED ISSUE #75: Missing items found when updating Go code
There was a breaking change in `utils/src/jailing.rs` in how `JailingDuration` was stored. This was not in the Changelog. More than the minor issue of updating the changelog, it shows a tricky case we should ensure our automated tooling detects (check for this in https://github.com/confio/poe-contracts/pull/74)

In valset, `SimulateActiveValidators` is exposed in the production build. This seems too critical a contract to leave such a test entry point in, even if there are auth guards. Let's do this (see original comment: https://github.com/confio/poe-contracts/pull/61#discussion_r797952726)

### PR DESCRIPTION
**Pull request by uint**
Closes #75

### CODE REVIEW

**Review by ethanfrey — APPROVED** [review]
lgtm. does this not break any tests?

oh, it is just used in integration tests, right? Curious how the build process works (does it happen in CI, is it checked in?)

Basically, this looks good. Please check Wirth @maurolacy on how the integration test is set up via the CI

**Comment by ethanfrey** [comment]
Is this the same as https://github.com/confio/poe-contracts/pull/77 ?

**Comment by maurolacy** [comment]
> Is this the same as #77 ?

Yes, it is. Working on it, as I don't see a clear path forward for this yet.

Perhaps remove this entry point entirely, and revisit later?

**Comment by uint** [comment]
> > Is this the same as #77 ?
> 
> Yes, it is.

Ah, okay! Happy to close this one then.

**Pull request closed without merging**
