### PR TITLE
Update rust toolchain to v1.58.1

### PR DESCRIPTION
**Pull request by uint**
To fix current CI failures:

https://app.circleci.com/pipelines/github/confio/poe-contracts/153/workflows/1570fcfa-349d-4fcc-9820-ff2338401711/jobs/2330

### CODE REVIEW

**Comment by maurolacy** [comment]
This works, but why not take the opportunity and upload all CI workflows to work with current stable (v1.58.1)?

**Comment by uint** [comment]
> This works, but why not take the opportunity and upload all CI workflows to work with current stable (v1.58.1)?

I guess I wanted to be cautious. Sure, will do.

**Comment by ethanfrey** [comment]
We generally try to keep this behind for a bit, as whatever the CI says is the "lowest supported version". We don't need to make cosmwasm devs update every few weeks.

However, I guess when we do update, everyone has to update, so maybe we do jump a bit? We should record lowest supported version in the README (and match cw-plus if possible)

**Comment by maurolacy** [comment]
cw-plus is already working with 1.58.1. The next rust-optimizer will ship with this version as well, so, good to move to it.

**Review by maurolacy — APPROVED** [review]
LGTM.

**Pull request merged**
